.github/workflows/ci.yml
CMakeLists.txt
mrdox-config.cmake.in

fix #139
This PR adapts CMakeLists.txt to create packages with cpack and adapts the GHA workflow to create a release with these packages whenever a tag is created or a commit is pushed to develop or master. The previous develop or master releases are always overridden.

generate github releases

---

.github/workflows/ci.yml

This PR reenables the MSVC workflow and fetches the LLVM binaries from a GitHub release stored in this repository. 
This means the MSVC workflow can also safely run in pull requests now.

LLVM comes from GitHub release

---

.github/workflows/ci.yml

This PR adds release notes to the body message in releases. It generates an automated changelog from commits. Although automated changelogs are not as good as manually written logs, they are definitely better than the automatic message we have now:
It's also something we can start with and edit and, at worst, it's a reminder of what changed so we can choose what to include in the changelog.
This task ended up being way more difficult than it looks because of 1) the ducktape to make the scripts work properly, 2) the usual turnaround to find errors in CI, and 3) a few bugs on the way that needed to be fixed, including a) a bug related to the location where llvm was being installed on Windows, which was triggering an error in CMake and corrupting the installer; b) another error related to …

Improved release notes body in releases

---

.github/workflows/ci.yml

This PR updates ci.yml to use the latest actions for the workflows.
This is a non-functional change: the latest [changes](https://github.com/alandefreitas/cpp-actions/releases/tag/v1.2.0)
in the actions should only make it faster and more stable.

ci: update workflows

---

.github/workflows/ci.yml
CMakeLists.txt
docs/modules/ROOT/pages/install.adoc

This PR extends the documentation about other dependencies and adds FetchContent support for fmt.

build: extend fmt integration options

---

.github/workflows/ci.yml

Among [changes](https://github.com/alandefreitas/cpp-actions/releases/tag/v1.5.0) with many bug fixes and performance improvements in all actions, the new setup-cpp step now sets up official apt repositories whenever possible for the compiler version being set. 
In practice, this allows all the most recent compiler versions to be set up with APT rather than our custom binaries, which is not only faster but also fixes many of the unstable workarounds we had before, such as manually setting LD_LIBRARY_PATH and the standard library configuration flags.

ci: update cpp-actions to v1.5.0

---

include/mrdox/Support/Handlebars.hpp
src/lib/Support/Handlebars.cpp
src/test/lib/Support/Handlebars.cpp
src/test_suite/detail/decomposer.hpp
src/test_suite/diff.cpp
src/test_suite/test_suite.cpp
src/test_suite/test_suite.hpp
test-files/handlebars/features_test.adoc
test-files/handlebars/features_test.adoc.hbs
test-files/handlebars/record.adoc.hbs

This PR replicates the basic spec tests from https:github.com/handlebars-lang/handlebars.js/blob/4.x/spec/basic.js
Fortunately the C++ implementation passed most tests without any changes. A few bugs in corner cases related to double escapes, specific types of whitespace control, and tag options were fixed.
On the other hand, Handlebars.js includes many undocumented features that are only being implemented now as I find out about them. For instance, `&` can be used in tags as an alternative for disabling HTML escaping. This does not seem to be documented anywhere.
There are also cases that can't be supported by the C++ implementation right now but are worth to thinking about. Especifically, Handlebars.js allows the context objects to include functions that are executed as helpers. This …

handlebars basic spec tests

---

include/mrdox/Platform.hpp
include/mrdox/Support/Assert.hpp
src/lib/Support/Assert.cpp

prior to this, the breakpoint would be triggered in `Signals.inc` (so you would have to go up a few stack frames to get to the source location of the assert)

Better assertions

---

include/mrdox/Dom/Function.hpp
include/mrdox/Dom/Function.ipp
include/mrdox/Support/Handlebars.hpp
src/lib/Support/Handlebars.cpp
src/test/lib/Support/Handlebars.cpp

Reference: https://github.com/handlebars-lang/handlebars.js/blob/4.x/spec/builtins.js
The main difference between this and what we had before these tests is helpers now support `dom::Function` to be completely according to spec.

feat: handlebars builtin specs

---

include/mrdox/Dom/Array.hpp
include/mrdox/Dom/Array.ipp
include/mrdox/Dom/Function.hpp
include/mrdox/Dom/Function.ipp
include/mrdox/Dom/Kind.hpp
include/mrdox/Dom/Object.hpp
include/mrdox/Dom/Object.ipp
include/mrdox/Dom/String.hpp
include/mrdox/Dom/Value.hpp
include/mrdox/Support/Error.hpp
include/mrdox/Support/Handlebars.hpp
share/gdb/mrdox_printers.py
src/lib/Dom/Array.cpp
src/lib/Dom/Function.cpp
src/lib/Dom/Object.cpp
src/lib/Dom/Value.cpp
src/lib/Metadata/DomMetadata.cpp
src/lib/Support/Handlebars.cpp
src/lib/Support/JavaScript.cpp
src/test/lib/Support/Handlebars.cpp
test-files/handlebars/features_test.adoc
test-files/handlebars/features_test.adoc.hbs

This PR refactors the handlebars engine to directly use regular `dom::Function`s as helpers. This also implies the helper callbacks became regular `dom::Object`s, which makes javascript bindings much simpler. It also allows native helpers to better interoperate with helpers defined in the context object. Because handlebars rely on helpers for everything, this ended up being the biggest refactor in the library so far.

feat: handlebars support dom::Function

---

include/mrdox/Dom/Function.hpp
include/mrdox/Dom/Function.ipp
include/mrdox/Support/Error.hpp
include/mrdox/Support/Handlebars.hpp
include/mrdox/Support/Lua.hpp
src/lib/-HTML/Builder.cpp
src/lib/-HTML/HTMLGenerator.cpp
src/lib/-HTML/Options.cpp
src/lib/-adoc/AdocGenerator.cpp
src/lib/-adoc/Builder.cpp
src/lib/-adoc/Options.cpp
src/lib/AST/BitcodeReader.cpp
src/lib/Lib/ConfigImpl.cpp
src/lib/Lib/CorpusImpl.cpp
src/lib/Support/Handlebars.cpp
src/lib/Support/JavaScript.cpp
src/lib/Support/Lua.cpp
src/lib/Support/Path.cpp
src/test/TestRunner.cpp
src/test/lib/Support/Handlebars.cpp
src/test_suite/test_suite.hpp

This PR implements handlebars support for error propagation using `Expected`. In MrDox, this implies that errors can be reported, and processing can proceed, enabling the user to address all issues in a single run rather than running MrDox repeatedly. The `Expected` class was adapted to conform better with `std::expected`, which includes extra features we needed, such as `Expected<void>`.
In the Handlebars sub-library, this PR includes support for helpers to return errors that are propagated to the parent context. This PR also completes all features needed for implementing the Javascript and Lua bindings for MrDox. After integrating the bindings, we can consider moving handlebars to a standalone library since it's a low-hanging fruit. The independent library could include extra features …

feat: handlebars error handling

---

include/mrdox/Support/JavaScript.hpp
share/mrdox/addons/generator/asciidoc/helpers/add.js
src/lib/-HTML/Builder.cpp
src/lib/-HTML/Builder.hpp
src/lib/-adoc/AdocGenerator.cpp
src/lib/-adoc/Builder.cpp
src/lib/-adoc/Builder.hpp
src/lib/Support/JavaScript.cpp

This PR refactors the asciidoc and html generators to use the C++ implementation of handlebars. Javascript helpers are loaded with duktape.

refactor: MrDox uses C++ handlebars

---

src/lib/Support/Handlebars.cpp
src/test/lib/Support/Handlebars.cpp

The unnecessary trim_spaces(expression) was removed from Handlebars.cpp as it's not required in the current context and could potentially remove intentional characters from literal string.

fix: remove expression trim

---

include/mrdox/Dom/Object.hpp
include/mrdox/Dom/Value.hpp
include/mrdox/Support/JavaScript.hpp
src/lib/-HTML/Builder.cpp
src/lib/-adoc/Builder.cpp
src/lib/Dom/Value.cpp
src/lib/Support/JavaScript.cpp
src/test/Support/Javascript.cpp

This PR implements unit tests for the Javascript bindings based on duktape. All errors found are fixed in the same commit.
This commit also includes the complete implementation for classes that were only placeholders, including conversions to dom::Value and related wrapper classes for objects, arrays, and functions.
The changes are only related to bindings from Javascript to C++. Bindings from C++ to Javascript will be addressed in a later commit.

test: JavaScript unit tests

---

.github/workflows/ci.yml
src/lib/Support/Handlebars.cpp

The handlebars engine needs to use string_view::data() instead of string_view::begin() on MSVC.

Handlebars engine uses string_view::data

---

.github/workflows/ci.yml
CMakeLists.txt
CMakePresets.json
CMakeUserPresets.json.example
docs/modules/ROOT/pages/install.adoc
mrdocs-config.cmake.in
vcpkg.json.example

This commit changes the Duktape setup to use the CMake find_package command to locate and configure the Duktape library. Direct access to source files through DUKTAPE_SOURCE_ROOT has been removed in order to respond to Duktape providing its own CMake integration scripts via vcpkg.
Additionally, installation instructions for Duktape and references to DUKTAPE_SOURCE_ROOT have been removed from relevant files and examples. Instead, the Duktape dependency is now managed by vcpkg in CI. This simplifies the setup of the development environment.

build: use duktape package

---

src/lib/Support/JavaScript.cpp
src/test/Support/JavaScript.cpp

This PR completes the proxy types for dom::Function, dom::Object, and dom::Array. This means all js::Value and dom::Value objects can be converted back and forth. 
The only current limitation is duktape [does not support](https://github.com/svaarala/duktape/issues/2153) iterating Proxy object keys with the "ownKeys" callback, which limits virtualized objects. In practice, this means more complex JS scripts might not work well with proxy objects that originally came from C++ dom::Value. Although this is fortunately not a problem we currently have, I already reached out to find a solution to this problem.
The next step is to adapt the logic for handlebars helpers to be able to return non-primitive types.

feat: C++/JS proxy arrays

---

CMakeUserPresets.json.example
include/mrdocs/Support/JavaScript.hpp
include/mrdocs/Support/Path.hpp
share/mrdocs/addons/generator/html/helpers/add.js
src/lib/Gen/adoc/Builder.cpp
src/lib/Gen/html/Builder.cpp
src/lib/Support/JavaScript.cpp
src/test/Support/JavaScript.cpp

This commit uses proxy objects to offer complete support for JavaScript helpers that return reference types. Previously, JavaScript reference types returned by these functions were deep-copied or not handled at all. Now, proxy objects in both directions are used while helpers create a scope that's kept alive as long as necessary by the Handlebars engine.
As the objects don't need to be deep copied, this change improves performance and allows objects with circular references, which are common in MrDocs. Additionally, JavaScript helpers receive a proxy object equivalent to the handlebars `options` object, and helper function registration was also simplified and improved to remove redundant code.
This commit provides new test cases to validate the current code without counting on MrDocs.

feat: complete JavaScript helpers support

---

include/mrdocs/Config.hpp
include/mrdocs/Support/Error.hpp
include/mrdocs/Support/Path.hpp
share/mrdocs/addons/generator/asciidoc/partials/source.adoc.hbs
src/lib/Gen/adoc/Builder.cpp
src/lib/Lib/ConfigImpl.cpp
src/lib/Lib/ConfigImpl.hpp
src/lib/Support/Path.cpp
src/tool/Addons.cpp
src/tool/Addons.hpp
src/tool/GenerateAction.cpp
src/tool/ToolMain.cpp

This PR gives templates access to the config values from mrdocs.yml. It also creates a new config key for setting the base URL so that the "Declared in header" templates can include a link to the declaration.

feat: templates have access to config

---

.github/workflows/ci.yml
src/lib/AST/ASTVisitor.cpp
src/lib/Lib/ConfigImpl.cpp
src/lib/Lib/ConfigImpl.hpp
src/lib/Lib/CorpusImpl.cpp
src/lib/Support/Glob.cpp
src/lib/Support/Glob.hpp

This PR implements the input filters needed by Boost.URL. 
Example:
```yaml
input:
include:
- ../include
file-patterns:
- '*.hpp'
```
which would be equivalent to the doxygen options `INPUT` and `FILE_PATTERNS`.

feat: input filters

---

CMakePresets.json
include/mrdocs/Metadata/Javadoc.hpp
share/mrdocs/addons/generator/asciidoc/partials/symbols/record.adoc.hbs
src/lib/AST/AnyBlock.hpp
src/lib/AST/ParseJavadoc.cpp
src/lib/AST/ParseJavadoc.hpp
src/lib/Gen/adoc/AdocCorpus.cpp
src/lib/Gen/adoc/Options.cpp
src/lib/Gen/xml/XMLWriter.cpp
src/lib/Gen/xml/XMLWriter.hpp
src/lib/Lib/ExecutionContext.cpp
src/lib/Metadata/Javadoc.cpp

This PR includes support for tags that are used in Boost.URL but are currently ignored by MrDocs.

feat: support extra javadoc tags

---

.github/workflows/ci.yml
docs/modules/ROOT/pages/install.adoc
third-party/llvm/CMakePresets.json

Generalizes the build process for any LLVM version and any set of configuration options. To make it faster, the set of targets is reduced to only what we need for MrDocs. When we change the LLVM parameters, the first run will take slightly longer in CI and subsequent runs will reuse the cached binaries. This means we no longer need to host the binaries on mrdocs.com and update them manually, making the process of updating the LLVM version much simpler and cheaper since github will be hosting the binaries. It also allows us to explore other static ways to build LLVM in CI, which is required to create executables that are not associated with a specific ubuntu version.
fix #548

ci: build and cache LLVM from source

---

.github/workflows/ci.yml
CMakeLists.txt
docs/antora-playbook.yml
docs/local-antora-playbook.yml
docs/modules/ROOT/pages/install.adoc
third-party/duktape/CMakeLists.txt
third-party/duktape/duktapeConfig.cmake.in

This PR is a continuation of #552 as an intermediary step to fix #547. It updates the CI workflow and the installation instructions so that they do not necessarily depend on VcPkg (although it's still an option) to install dependencies. The motivation is to be able to customize how these dependencies are built to later be able to build MrDocs with one of the strategies listed in #547.

Use official dependency releases

---

.github/workflows/ci.yml
docs/modules/ROOT/pages/install.adoc

This extends the same logic of other dependencies and avoids bugs in the vcpkg port.

ci: use official libxml2 release

---

src/lib/AST/ASTVisitor.cpp

This was fixed in clang (https://github.com/llvm/llvm-project/pull/68222)

Remove USR generation workaround for decayed function parameters

---

.github/workflows/ci.yml
docs/modules/ROOT/pages/install.adoc
include/mrdocs/Dom/Object.hpp
src/lib/AST/ParseJavadoc.cpp
src/lib/Dom/Object.cpp
src/lib/Gen/adoc/AdocCorpus.cpp
src/lib/Gen/html/HTMLCorpus.cpp
src/lib/Lib/ExecutionContext.cpp
src/lib/Lib/SingleFileDB.hpp
src/lib/Metadata/Finalize.cpp
src/tool/ToolMain.cpp

This PR fixes a number of minor warnings and problems we had.

Warnings and fixes

---

.github/workflows/ci.yml
CMakeLists.txt

This PR updates known_hosts permissions to 600 to avoid errors uploading to the website. CMakeLists.txt gives the capitalized version of the duktape package higher precedence to avoid unnecessary warnings locally and in CI.

CI minor issues

---

.github/workflows/ci.yml
src/test/TestRunner.cpp
src/tool/ToolArgs.cpp
src/tool/ToolArgs.hpp

The runner image has been updated, and it's now possible to fix the LLVM build step and test segfaults that previously blocked CI. So, this PR includes some minor changes in CI related to errors in generating demos and releases. It also fixes GCC/Clang warnings in passing.

CI: fix demos and releases

---

src/lib/AST/ASTVisitor.cpp

Fixes #665. Note that this fix isn't perfect as it does not handle cases where the recursion period is greater than one.

fix: infinite recursion when identifying SFINAE types

---

docs/modules/ROOT/pages/usage.adoc

Replace `OUTPUT_FILE` with `TMP_CPP_FILE` in the Cmake example for header-only libraries, so that it compiles.

Docs: Fix Cmake example in usage.adoc

---

share/mrdocs/addons/generator/asciidoc/partials/symbols/function.adoc.hbs
share/mrdocs/addons/generator/asciidoc/partials/symbols/record.adoc.hbs

Fixes https://github.com/cppalliance/mrdocs/issues/674

fix: missing template parameters in asciidoc templates

---

.github/workflows/ci.yml
docs/modules/ROOT/pages/install.adoc
include/mrdocs/Dom/Object.hpp
include/mrdocs/Platform.hpp
src/lib/Dom/Object.cpp
src/lib/Lib/CMakeExecution.cpp
src/lib/Lib/MrDocsCompilationDatabase.cpp
src/lib/Support/Error.cpp

ci: enable macos and blocking issues

---

.github/workflows/ci.yml
docs/modules/ROOT/attachments/mrdocs.schema.json
docs/modules/ROOT/pages/config-file.adoc
docs/modules/ROOT/partials/mrdocs-schema-example.yml
docs/mrdocs.schema.json
docs/mrdocs.yml
util/generate-yaml-schema.py

This PR extends `generate-config-info.py` to generate a YAML/JSON schema for the config file. As explained in the issue, this can be used to provide autocompletion and linting. The "YAML schema" is just a [JSON schema](https://json-schema.org).
Currently, the schema is committed to the repo. I'm not sure if that's desired. The main upside of this is, that users can link to the schema using (raw) GitHub links. This allows linking to tags, but most importantly it allows linking to specific commits. However, there's now duplicate information in the repo. CI ensures the schema is always up-to-date, though.
Alternatively, this could be done as part of the Antora build (probably, I'm not that familiar with it).
Closes #700.

feat: generate YAML schema for config

---

src/lib/Lib/CorpusImpl.cpp
src/lib/Lib/CorpusImpl.hpp
src/test/TestRunner.cpp
src/tool/GenerateAction.cpp

Fixes https://github.com/cppalliance/mrdocs/issues/691

feat: uniform logging level control across CorpusImpl

---

share/mrdocs/addons/generator/adoc/layouts/wrapper.adoc.hbs
share/mrdocs/addons/generator/adoc/partials/markup/a.adoc.hbs
share/mrdocs/addons/generator/adoc/partials/symbol.adoc.hbs
share/mrdocs/addons/generator/common/partials/symbol/detail/members-table-row.hbs
share/mrdocs/addons/generator/common/partials/symbol/name-info.hbs
share/mrdocs/addons/generator/common/partials/symbol/name.hbs
share/mrdocs/addons/generator/common/partials/symbol/qualified-name.hbs
share/mrdocs/addons/generator/common/partials/symbol/signatures.hbs
share/mrdocs/addons/generator/common/partials/template/arg.hbs
share/mrdocs/addons/generator/html/partials/markup/a.html.hbs
test-files/golden-tests/brief-1.adoc
test-files/golden-tests/enum.adoc
test-files/golden-tests/ref.adoc

see https://gitlab.com/antora/antora/-/issues/428

fix: no relative asciidoc links

---

docs/mrdocs.schema.json
include/mrdocs/Corpus.hpp
include/mrdocs/Generator.hpp
src/lib/Gen/hbs/HandlebarsGenerator.cpp
src/lib/Gen/xml/XMLTags.cpp
src/lib/Gen/xml/XMLTags.hpp
src/lib/Lib/ConfigOptions.json
src/lib/Lib/TagfileWriter.cpp
src/lib/Lib/TagfileWriter.hpp
src/lib/Support/Generator.cpp

Fixes https://github.com/cppalliance/mrdocs/issues/650

feat: tagfiles generation for cross-referencing in doxygen format

---

include/mrdocs/Metadata/Concept.hpp
include/mrdocs/Metadata/Function.hpp
include/mrdocs/Metadata/Guide.hpp
include/mrdocs/Metadata/Record.hpp
include/mrdocs/Metadata/Template.hpp
include/mrdocs/Metadata/Typedef.hpp
include/mrdocs/Metadata/Variable.hpp
src/lib/AST/ASTVisitor.cpp
src/lib/AST/ASTVisitor.hpp
src/lib/Gen/xml/XMLWriter.cpp
src/lib/Gen/xml/XMLWriter.hpp
src/lib/Metadata/Finalize.cpp

unify traverse functions

---

src/lib/AST/ParseJavadoc.cpp
test-files/golden-tests/para-3.adoc
test-files/golden-tests/para-3.cpp
test-files/golden-tests/para-3.html
test-files/golden-tests/para-3.xml

`\par` accepts the heading as the first argument.
Fixes https://github.com/cppalliance/mrdocs/issues/765.
Aside: I noticed that the tests for the adoc and HTML generators are taking much longer than the XML tests (also visible in CI).

fix: use arguments to `\par` if available

---

include/mrdocs/Metadata/Javadoc.hpp
src/lib/AST/ParseJavadoc.cpp
src/lib/Gen/hbs/HandlebarsCorpus.cpp
test-files/golden-tests/core/libcxx.adoc
test-files/golden-tests/core/libcxx.html
test-files/golden-tests/core/libcxx.xml
test-files/golden-tests/javadoc/throw.adoc
test-files/golden-tests/javadoc/throw.cpp
test-files/golden-tests/javadoc/throw.html
test-files/golden-tests/javadoc/throw.xml
test-files/golden-tests/metadata/overloads.adoc
test-files/golden-tests/metadata/overloads.cpp
test-files/golden-tests/metadata/overloads.html
test-files/golden-tests/metadata/overloads.xml
test-files/golden-tests/snippets/sqrt.adoc
test-files/golden-tests/snippets/sqrt.html
test-files/golden-tests/snippets/sqrt.xml

support throw symbols

---

src/lib/Lib/Config.cpp
src/lib/Lib/ConfigOptions.json
src/tool/ToolMain.cpp
util/generate-config-info.py

ToolArgs include no default strings

---

include/mrdocs/Metadata/Template.hpp
src/lib/AST/ASTVisitor.cpp
src/lib/AST/ASTVisitor.hpp
src/lib/AST/ClangHelpers.hpp
src/lib/AST/NameInfoBuilder.cpp
src/lib/AST/TerminalTypeVisitor.hpp
src/lib/AST/TypeInfoBuilder.cpp
src/lib/Gen/adoc/AdocGenerator.cpp
src/lib/Gen/adoc/AdocGenerator.hpp
src/lib/Gen/hbs/HandlebarsGenerator.cpp
src/lib/Gen/hbs/HandlebarsGenerator.hpp
src/lib/Gen/html/HTMLGenerator.cpp
src/lib/Gen/html/HTMLGenerator.hpp
src/lib/Lib/TagfileWriter.cpp
src/lib/Lib/TagfileWriter.hpp
src/test/TestRunner.cpp
test-files/golden-tests/metadata/class-private-alias.adoc
test-files/golden-tests/metadata/class-private-alias.cpp
test-files/golden-tests/metadata/class-private-alias.html
test-files/golden-tests/metadata/class-private-alias.xml
test-files/golden-tests/metadata/function-template-template.adoc
test-files/golden-tests/metadata/function-template-template.cpp
test-files/golden-tests/metadata/function-template-template.html
test-files/golden-tests/metadata/function-template-template.xml

function template template parameters

---

src/lib/Gen/adoc/AdocEscape.cpp
test-files/golden-tests/javadoc/ref.adoc

asciidoc tilde escaped as U+007E

---

include/mrdocs/Metadata/Javadoc.hpp
include/mrdocs/MetadataFwd.hpp
mrdocs.rnc
src/lib/AST/ParseJavadoc.cpp
src/lib/Gen/adoc/DocVisitor.cpp
src/lib/Gen/adoc/DocVisitor.hpp
src/lib/Gen/html/DocVisitor.cpp
src/lib/Gen/html/DocVisitor.hpp
src/lib/Gen/xml/XMLWriter.cpp
src/lib/Gen/xml/XMLWriter.hpp
test-files/golden-tests/javadoc/li.adoc
test-files/golden-tests/javadoc/li.cpp
test-files/golden-tests/javadoc/li.html
test-files/golden-tests/javadoc/li.xml

support unordered lists

---

docs/modules/ROOT/pages/usage.adoc
src/lib/Lib/CMakeExecution.cpp

honor user CMAKE_EXPORT_COMPILE_COMMANDS in cmake option

---

docs/modules/ROOT/pages/config-file.adoc

#feat
See https://github.com/SchemaStore/schemastore/commit/28d4076c4f6bec301ad8c747737377e5a36bdfc7
fix #772

MrDocs in schema store

---

src/lib/AST/ASTVisitor.cpp
test-files/golden-tests/metadata/sfinae.adoc
test-files/golden-tests/metadata/sfinae.cpp
test-files/golden-tests/metadata/sfinae.html
test-files/golden-tests/metadata/sfinae.xml

support void_t SFINAE

---

docs/mrdocs.schema.json
docs/website/render.js
docs/website/snippets/mrdocs.yml
src/lib/Gen/hbs/HandlebarsCorpus.cpp
src/lib/Gen/hbs/MultiPageVisitor.cpp
src/lib/Gen/hbs/SinglePageVisitor.cpp
src/lib/Gen/hbs/VisitorHelpers.cpp
src/lib/Gen/hbs/VisitorHelpers.hpp
src/lib/Lib/Config.cpp
src/lib/Lib/ConfigOptions.json
src/lib/Lib/TagfileWriter.cpp
src/lib/Metadata/Finalizers/ReferenceFinalizer.cpp
test-files/golden-tests/config/show-namespaces/show-namespaces.adoc
test-files/golden-tests/config/show-namespaces/show-namespaces.cpp
test-files/golden-tests/config/show-namespaces/show-namespaces.html
test-files/golden-tests/config/show-namespaces/show-namespaces.xml
test-files/golden-tests/config/show-namespaces/show-namespaces.yml
test-files/golden-tests/snippets/distance.adoc
test-files/golden-tests/snippets/distance.html
test-files/golden-tests/snippets/is_prime.adoc
test-files/golden-tests/snippets/is_prime.html
test-files/golden-tests/snippets/mrdocs.yml
test-files/golden-tests/snippets/sqrt.adoc
test-files/golden-tests/snippets/sqrt.html
test-files/golden-tests/snippets/terminate.adoc
test-files/golden-tests/snippets/terminate.html
util/generate-config-info.py

show-namespaces option 

---

include/mrdocs/Metadata/Javadoc.hpp
mrdocs.rnc
share/mrdocs/addons/generator/adoc/partials/symbol.adoc.hbs
src/lib/AST/ParseJavadoc.cpp
src/lib/Gen/adoc/DocVisitor.cpp
src/lib/Gen/hbs/HandlebarsCorpus.cpp
src/lib/Gen/html/DocVisitor.cpp
src/lib/Gen/xml/XMLWriter.cpp
src/lib/Gen/xml/XMLWriter.hpp
src/lib/Metadata/Finalizers/JavadocFinalizer.cpp
src/lib/Metadata/Javadoc.cpp
test-files/golden-tests/javadoc/relates/relates.adoc
test-files/golden-tests/javadoc/relates/relates.cpp
test-files/golden-tests/javadoc/relates/relates.html
test-files/golden-tests/javadoc/relates/relates.xml

This needs a clang patch that marks `@relates` as an inline comment command.

feat: support @relates

---

include/mrdocs/ADT/Optional.hpp
include/mrdocs/ADT/Polymorphic.hpp
include/mrdocs/Metadata/Info/Function.hpp
include/mrdocs/Metadata/Type.hpp
include/mrdocs/Support/Algorithm.hpp
share/mrdocs/addons/generator/common/partials/type/declarator-prefix.hbs
src/lib/AST/ASTVisitor.cpp
src/lib/AST/ParseRef.cpp
src/lib/AST/ParseRef.hpp
src/lib/AST/TypeInfoBuilder.cpp
src/lib/Gen/xml/CXXTags.hpp
src/lib/Lib/TagfileWriter.cpp
src/lib/Metadata/Finalizers/JavadocFinalizer.cpp
src/lib/Metadata/Info/Function.cpp
src/lib/Metadata/Type.cpp
src/test/lib/AST/ParseRef.cpp

javadoc ref parser supports function parameters

---

src/lib/AST/ParseJavadoc.cpp
test-files/golden-tests/javadoc/copydoc/qualifiers.adoc
test-files/golden-tests/javadoc/copydoc/qualifiers.cpp
test-files/golden-tests/javadoc/copydoc/qualifiers.html
test-files/golden-tests/javadoc/copydoc/qualifiers.xml

javadoc parser extracts ref qualifiers

---

src/lib/Lib/CorpusImpl.cpp
test-files/golden-tests/javadoc/copydoc/qualified.adoc
test-files/golden-tests/javadoc/copydoc/qualified.cpp
test-files/golden-tests/javadoc/copydoc/qualified.html
test-files/golden-tests/javadoc/copydoc/qualified.xml

ref parameter match supports arbitrarily qualified names

---

include/mrdocs/Config.hpp
include/mrdocs/Support/Algorithm.hpp
include/mrdocs/Support/Path.hpp
src/lib/Lib/Config.cpp
src/lib/Support/Path.cpp
src/lib/Support/Path.hpp
src/tool/GenerateAction.cpp

ScopedTempDirectory stores error type

---

include/mrdocs/Metadata/Javadoc.hpp
mrdocs.rnc
share/mrdocs/addons/generator/adoc/partials/symbol.adoc.hbs
share/mrdocs/addons/generator/html/partials/symbol.html.hbs
src/lib/AST/ParseJavadoc.cpp
src/lib/Gen/xml/CXXTags.hpp
src/lib/Gen/xml/XMLWriter.cpp
src/lib/Gen/xml/XMLWriter.hpp
src/lib/Metadata/Finalizers/JavadocFinalizer.cpp
src/lib/Metadata/Finalizers/JavadocFinalizer.hpp
src/lib/Metadata/Javadoc.cpp
test-files/golden-tests/javadoc/relates/relates.adoc
test-files/golden-tests/javadoc/relates/relates.html
test-files/golden-tests/javadoc/relates/relates.xml
test-files/golden-tests/symbols/enum/enum.adoc

preprocess related symbols

---

src/lib/AST/ASTVisitor.cpp
src/lib/Metadata/Finalizers/BaseMembersFinalizer.cpp
test-files/golden-tests/config/inherit-base-members/skip-special.adoc
test-files/golden-tests/config/inherit-base-members/skip-special.cpp
test-files/golden-tests/config/inherit-base-members/skip-special.html
test-files/golden-tests/config/inherit-base-members/skip-special.xml
test-files/golden-tests/config/inherit-base-members/skip-special.yml

Small fixes on the symbol filters that were effecting Boost.URL

symbol filter: small fixes

---

src/lib/AST/ASTVisitor.cpp
test-files/golden-tests/symbols/record/class-template-specializations-1.adoc
test-files/golden-tests/symbols/record/class-template-specializations-1.html
test-files/golden-tests/symbols/record/class-template-specializations-1.xml
test-files/golden-tests/symbols/record/template-specialization-inheritance.adoc
test-files/golden-tests/symbols/record/template-specialization-inheritance.html
test-files/golden-tests/symbols/record/template-specialization-inheritance.xml

redundant Decls use least specific extraction mode

---

src/lib/Lib/ExecutionContext.cpp

I'm not 100% sure if this is the correct approach. I would guess that something like this already happens somewhere, but I couldn't find anything.
When using multiple sources (→ multiple extraction jobs), then only the first one will be "visible", because its global namespace/global symbol will be the only one that gets merged with `info_.merge(info)`. All other global namespaces will be discarded, because there's already one present. Their members will still be in the corpus, but there's no path from the global symbol to them.
Because of ODR, only namespaces have to be merged.

fix: merge namespaces when collecting results

---

docs/modules/ROOT/pages/contribute.adoc
docs/modules/ROOT/pages/install.adoc
docs/modules/ROOT/pages/usage.adoc

This fixes a few misc problems (typos, extraneous words, etc.).

Fix some glitches in the documentation

---

src/lib/Lib/CMakeExecution.cpp
src/lib/Lib/ExecuteAndWaitWithLogging.cpp
src/lib/Lib/ExecuteAndWaitWithLogging.hpp
src/lib/Lib/MrDocsCompilationDatabase.cpp
src/test/TestRunner.cpp
src/tool/CompilerInfo.cpp

Print all external commands

---

src/lib/Metadata/Finalizers/Javadoc/Function.hpp

isCopyOrMoveConstructorOrAssignment currently doesn't handle a constructor from a reference to array. I am not sure why this is not seen on CI, but it is reproducible from llvm 20.1.7, as available in macos homebrew.

fix: handle constructor from reference to array

---

src/lib/Metadata/Finalizers/OverloadsFinalizer.cpp
src/lib/Metadata/Info/Overloads.cpp

I am not sure why this is not seen in CI presently, but I can reproduce it when building mrdocs from the llvm version bundled in homebrew (currently 20.1.7).

fix: crash on unimplemented when populating overloads destructor entry

---

include/mrdocs/Support/Handlebars.hpp
src/test_suite/detail/decomposer.hpp

use is_formattable instead.
has_formatter was never a good API, since it only asked if the type has a `formatter` specialization, but a type can also be formattable if it provides an implicit conversion to a type which does.
The newer API takes care of the that problem.

fix: replace uses of deprecated fmt::has_formatter

---

CMakePresets.json
bootstrap.py
docs/modules/ROOT/pages/install.adoc

The bootstrap script provides a single source of truth for the installation steps described in install.adoc.

build: bootstrap script

---

.github/workflows/ci.yml

This also:
* Makes sure the ubuntu clang builds have libstdc++-14 installed, which is our minumum.
* Bumps cpp-actions to v1.8.10.
* Use the newest Xcode for MacOS.

ci: add newer compilers to the matrix

---

.github/workflows/ci.yml
src/lib/Metadata/Finalizers/BaseMembersFinalizer.cpp
src/lib/Support/Yaml.cpp
src/lib/Support/Yaml.hpp

And fixes a member function call through a null pointer and an incorrect use of static_cast.

ci: enable ubsan for clang and gcc

---

.github/workflows/ci.yml

Also fixes sanitizer variable usage on llvm-archive-basename.
The setting for LLVM_ENABLE_RTTI was also redundant, as it is always set by the cmake profiles.

ci: add clang UBSan and ASan to apple-clang job

---

CMakeLists.txt

LLVM_INCLUDE_DIRS can be a list of directories with more than one entry.
Quote the generator expressions so that list expansion doesn't happen before it is parsed.

build: quote genexp for target_include_directories

---

docs/ui/src/partials/logo.hbs
docs/website/index.html.hbs

This is just a little part of the overall work, but I'd like to receive a feedback before continuing. I'd also like to know which level of Accessibility the website should at least support, since, in some situations, this may also have an impact on the design. My idea is to keep the WCAG 2.2, Level AA. This should be a good trade-off between simplicity for development and a better UX for people with disabilities. Moreover, this should make the website conformant with the EAA (EN 301 549).
The `header-cta` links had "aria-label" attributes that essentially repeated what the information that can be retrieved by the text node. Also, the first link had a mismatch between what there was in the `aria-label` attribute ("Documentation") and what  there's in the text node ("Get Started").
The …

Accessibility improvements

---

bootstrap.py

I left the code as is, but we shouldn't hard-code directory names like that.

fix: bootstrap uses the directory of the latest includes available under `llvm_install_dir` for `--stdlib-includes`

---

docs/mrdocs.schema.json
src/lib/ConfigOptions.json
src/lib/CorpusImpl.cpp
src/lib/Metadata/Finalizers/SortMembersFinalizer.cpp
test-files/golden-tests/config/sort-members-by/sort-members-by-location.adoc
test-files/golden-tests/config/sort-members-by/sort-members-by-location.cpp
test-files/golden-tests/config/sort-members-by/sort-members-by-location.html
test-files/golden-tests/config/sort-members-by/sort-members-by-location.xml
test-files/golden-tests/config/sort-members-by/sort-members-by-location.yml
test-files/golden-tests/config/sort-members-by/sort-members-by-name.adoc
test-files/golden-tests/config/sort-members-by/sort-members-by-name.cpp
test-files/golden-tests/config/sort-members-by/sort-members-by-name.html
test-files/golden-tests/config/sort-members-by/sort-members-by-name.xml
test-files/golden-tests/config/sort-members-by/sort-members-by-name.yml
test-files/golden-tests/config/sort-namespace-members-by/sort-namespace-members-by-location.adoc
test-files/golden-tests/config/sort-namespace-members-by/sort-namespace-members-by-location.cpp
test-files/golden-tests/config/sort-namespace-members-by/sort-namespace-members-by-location.html
test-files/golden-tests/config/sort-namespace-members-by/sort-namespace-members-by-location.xml
test-files/golden-tests/config/sort-namespace-members-by/sort-namespace-members-by-location.yml
test-files/golden-tests/config/sort-namespace-members-by/sort-namespace-members-by-name.adoc
test-files/golden-tests/config/sort-namespace-members-by/sort-namespace-members-by-name.cpp
test-files/golden-tests/config/sort-namespace-members-by/sort-namespace-members-by-name.html
test-files/golden-tests/config/sort-namespace-members-by/sort-namespace-members-by-name.xml
test-files/golden-tests/config/sort-namespace-members-by/sort-namespace-members-by-name.yml
test-files/golden-tests/config/sort/unordered.adoc
test-files/golden-tests/config/sort/unordered.xml
test-files/golden-tests/config/sort/unordered.yml
util/generate-config-info.py

- `sort-members` no longer affects namespaces
- `sort-members-by` determines the criteria for sorting record members
- namespace members are always sorted
- `sort-namespace-members-by` determines the criteria for sorting namespace members

split record and namespace members sorting criteria

---

src/lib/MrDocsSettingsDB.hpp

That file used the same include guard macro as SingleFileDB.hpp.

Use a distinct include guard in MrDocsSettingsDB.hpp

---

.github/workflows/ci.yml
docs/website/robots.txt

This makes that step use rsync to upload the website and demos.
Besides supporting compression, rsync also only sends the changes
over the wire.
This improves the performance of that step by a wide margin, reducing
normal upload times from almost 9 minutes down to about 20s for the most
common changes.
Note we have seen some times this step take almost two hours, but it seems
circumstantial with unknown cause, and we are not sure what kind of improvement
this would have in that case.
This uses rsync's ability to also remove stale files, to make sure
we don't leave old files behind. (This ignores the directories which are
handled separately, like llvm+clang and demos).
There were some pretty stale things left behind that this now removes,
such as a sitemap.xml which was generated last …

ci: improve the 'Publish website' step

---

src/lib/AST/ASTVisitor.cpp
test-files/golden-tests/symbols/record/unnamed.adoc
test-files/golden-tests/symbols/record/unnamed.cpp
test-files/golden-tests/symbols/record/unnamed.html
test-files/golden-tests/symbols/record/unnamed.xml

These classes can appear as user written code and needs to be documented, as show in the new test case.
In general, for implementation defined declarations, we can detect them as the clang AST exposes them as 'implicit', but this is possible for any declaration, and can be handled more generally.
This is related to https://github.com/cppalliance/mrdocs/issues/1054: We have no way to mark these classes as implementation defined with this change.
This is also related to https://github.com/cppalliance/mrdocs/issues/1055, as the HTML generator has some issues printing unnamed entities.
Fixes #1035

don't mark unnamed classes as implementation defined
