cppalliance/mrdocs

.github/actions/boost_clone/action.yml, .github/actions/cmake_run/action.yml, .github/actions/package_install/action.yml, .github/workflows/ci.yml, .gitignore, .gitmodules, CMakeLists.txt, README.adoc, source/lib/CommentVisitor.cpp, source/lib/jad/Function.hpp, source/tests/TestFiles.hpp, source/tests/TestMain.cpp
This PR includes a workflow based on the `cppalliance/droneubuntu2204:llvm-731264b` container, which already comes with llvm+clang installed.
`Function.hpp` includes a small bug fix. The move constructor cannot be `noexcept` because the base and member classes don't have `noexcept` move constructors. This is an error in GCC.
`CommentVisitor.cpp` also includes a small bug fix. It was including the header `#include "CommentVisitor.h "`, with a whitespace in the end.
`CMakeLists.txt` includes the default CMake variables, that helped with making CI work.
Instructions to build the project, including llvm+clang, were included in `README.adoc`.
=> Continuous Integration

CMakeLists.txt, source/api/Version.hpp.in, source/tool/ToolMain.cpp
=> mrdox has a version to print

source/api/AST/ASTVisitor.cpp, test-files/old-tests/attributes_1.xml, test-files/old-tests/explicit-conv-operator.xml, test-files/old-tests/explicit-deduct-guide.xml
=> _Bool becomes `bool`

.github/workflows/ci.yml
This PR updates the workflow with the latest GCC and Clang compilers.
The action uses custom binaries to be able to offer these versions.
=> update CI matrix

.github/workflows/ci.yml
This PR updates the test matrix to use the latest cpp-actions v1.4.0. It includes the matrix generator and reports for test factors.
=> ci: update cpp-actions to v1.4.0

include/mrdox/Metadata/Source.hpp, source/AST/DecodeRecord.hpp
=> add OptionalLocation

.github/workflows/ci.yml, include/mrdox/Metadata/DomMetadata.hpp, include/mrdox/Metadata/Interface.hpp, include/mrdox/Support/Dom.hpp, include/mrdox/Support/JavaScript.hpp, include/mrdox/Support/Lua.hpp, include/mrdox/mrdox.natvis, source/-adoc/Builder.cpp, source/Metadata/DomMetadata.cpp, source/Metadata/Interface.cpp, source/Support/Dom.cpp, source/Support/JavaScript.cpp, source/Support/Lua.cpp, source/lua.cpp, test-files/adoc/test.cpp
This PR is basically the same as #354 with a few extra commits to fix warnings and problems. This could be merged as a new PR that deprecates #354 or cherry-picked into #354.
=> JavaScript Proxy and Lua

include/mrdox/Support/Handlebars.hpp, src/lib/Dom/Value.cpp, src/lib/Support/Handlebars.cpp, src/test/lib/Support/Handlebars.cpp, test-files/handlebars/features_test.adoc, test-files/handlebars/features_test.adoc.hbs
https://github.com/handlebars-lang/handlebars.js/blob/4.x/spec/whitespace-control.js
=> Handlebars whitespace control specs

include/mrdox/Support/Handlebars.hpp, share/gdb/README.adoc, share/gdb/__init__.py, share/gdb/mrdox_printers.py, src/lib/Support/Handlebars.cpp, src/test/lib/Support/Handlebars.cpp, test-files/handlebars/features_test.adoc
WIP because these specs are huge. 
And also hugely important.
=> feat: partials specs

share/gdb/mrdox_printers.py, src/lib/Dom/Value.cpp, src/lib/Support/Handlebars.cpp, src/test/lib/Support/Handlebars.cpp, test-files/handlebars/features_test.adoc, test-files/handlebars/logger_output.txt
https://github.com/handlebars-lang/handlebars.js/blob/4.x/spec/subexpressions.js
=> feat: subexpression specs

include/mrdox/Dom/Array.hpp, include/mrdox/Dom/Array.ipp, include/mrdox/Dom/Function.ipp, src/lib/Support/Handlebars.cpp, src/test/lib/Support/Handlebars.cpp, test-files/handlebars/features_test.adoc
"WIP" because this one is significantly larger than the others
=> feat: handlebars helpers specs

include/mrdox/Support/Error.hpp, include/mrdox/Support/Handlebars.hpp, src/lib/Support/Handlebars.cpp, src/test/lib/Support/Handlebars.cpp, test-files/handlebars/features_test.adoc, test-files/handlebars/features_test.adoc.hbs
This PR includes a number of features related to helper parameter IDs, such as block parameters, context paths, and accessing proper ids from helpers.
=> feat: handlebars track-ids specs

.github/workflows/ci.yml
After merging, there still may need to be a one-time update on the server side also.
=> Fix directory permissions for website indexing

include/mrdox/Dom/String.hpp, src/lib/Dom/String.cpp
=> store dom::String as a single pointer

share/mrdocs/addons/generator/asciidoc/layouts/overload-set.adoc.hbs, share/mrdocs/addons/generator/asciidoc/layouts/single-symbol.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/declarator-before.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/qualified-path.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/enum.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/function.adoc.hbs, src/lib/Lib/ConfigImpl.cpp
Fix missing qualified typedefs and a few related issues with the declarator.
=> docs: qualified typedefs

.github/workflows/ci.yml
Many features have been included and many bugs have been fixed since v1.5.0.
=> ci: update cpp-actions to v1.6.2

include/mrdocs/Corpus.hpp, include/mrdocs/Metadata/Info.hpp, include/mrdocs/Metadata/Scope.hpp, include/mrdocs/Metadata/Specifiers.hpp, include/mrdocs/Metadata/Symbols.hpp, include/mrdocs/Support/Visitor.hpp
Added Javadocs and did some cleanup incidentally while addressing other issues.
=> docs: Corpus javadocs

src/lib/Lib/CMakeExecution.cpp
Use a complete bash argument parser for the `cmake` config option.
=> refactor: bash argument parser

src/tool/ToolMain.cpp
Fixes https://github.com/cppalliance/mrdocs/issues/457
=> fix: bug reporters refer to Mrdocs repo

src/lib/AST/ASTVisitor.cpp, test-files/old-tests/dependency-propagation.cpp, test-files/old-tests/dependency-propagation.xml, test-files/old-tests/dependency-propagation.yml
=> Propagate current dependency mode when extracting typedefs as a dependency

share/mrdocs/addons/generator/asciidoc/partials/name-info.adoc.hbs, src/lib/AST/ASTVisitor.cpp, test-files/old-tests/class-template-specializations-1.xml, test-files/old-tests/class-template-specializations-3.xml, test-files/old-tests/dependency-propagation.xml, test-files/old-tests/implicit-instantiation-member-ref.xml, test-files/old-tests/record-data.xml, test-files/old-tests/ref.xml
=> build NameInfo using explicitly provided nested-name-specifier

share/mrdocs/addons/generator/asciidoc/partials/info-member.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/special-name-suffix.adoc.hbs
=> annotate constructors and destructors in adoc member lists

src/lib/AST/ParseJavadoc.cpp, src/lib/Gen/adoc/AdocCorpus.cpp
=> support @n command

include/mrdocs/Support/Handlebars.hpp, share/mrdocs/addons/generator/asciidoc/layouts/overload-set.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/signature/function.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/signature/record.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/signature/variable.adoc.hbs, src/lib/Gen/adoc/Builder.cpp, src/lib/Support/Handlebars.cpp
=> link names in overload sets

share/mrdocs/addons/generator/asciidoc/layouts/overload-set.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/nested-name-specifier.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/alias.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/enum.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/enumerator.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/field.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/friend.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/function.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/guide.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/namespace.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/record.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/typedef.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/using.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/variable.adoc.hbs
=> Show full nested-name-specifier in titles

src/lib/Gen/adoc/AdocCorpus.hpp, src/lib/Gen/adoc/AdocGenerator.cpp, src/lib/Gen/adoc/Builder.cpp, src/lib/Gen/adoc/Options.cpp, src/lib/Gen/adoc/Options.hpp, src/lib/Gen/bitcode/BitcodeGenerator.cpp, src/lib/Gen/html/HTMLGenerator.cpp, src/lib/Gen/html/Options.cpp, src/lib/Gen/html/Options.hpp, src/lib/Gen/xml/XMLWriter.cpp, src/lib/Gen/xml/XMLWriter.hpp, src/lib/Metadata/DomMetadata.cpp, src/lib/Metadata/Function.cpp, src/lib/Support/LegibleNames.cpp, src/lib/Support/LegibleNames.hpp
=> rename 'safe names' to 'legible names'

share/mrdocs/addons/generator/asciidoc/layouts/overload-set.adoc.hbs, share/mrdocs/addons/generator/asciidoc/layouts/single-symbol.adoc.hbs, src/lib/Gen/adoc/Builder.cpp
=> generate safe names for section ids

src/lib/AST/ASTVisitor.cpp
=> fix merging of parameter names

share/mrdocs/addons/generator/html/partials/namespace.html.hbs, share/mrdocs/addons/generator/html/partials/qualified-path.html.hbs, share/mrdocs/addons/generator/html/partials/special-name-suffix.html.hbs
=> chore: Asciidoc and HTML Template Synchronization

.github/workflows/ci.yml, include/mrdocs/Platform.hpp, src/lib/AST/ParseJavadoc.cpp, src/lib/Support/Radix.cpp
This PR adapts and rebases old PRs to the current codebase.
=> Rebase old PRs

share/mrdocs/addons/generator/asciidoc/partials/declarator-before.adoc.hbs, share/mrdocs/addons/generator/html/partials/declarator-before.html.hbs
=> East-const style applied to documentation generation

share/mrdocs/addons/generator/asciidoc/layouts/overload-set.adoc.hbs, share/mrdocs/addons/generator/asciidoc/layouts/page.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/info-list.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/alias.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/enum.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/enumerator.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/field.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/friend.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/function.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/guide.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/namespace.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/record.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/typedef.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/using.adoc.hbs, share/mrdocs/addons/generator/asciidoc/partials/symbols/variable.adoc.hbs, test-files/handlebars/features_test.adoc.hbs
Fixes [#653](https://github.com/cppalliance/mrdocs/issues/653)
=> Title conflict resolved in single-page Asciidoc template

.github/workflows/ci.yml, src/lib/Support/Handlebars.cpp, src/test/lib/Support/Handlebars.cpp
Support whitespace control to blocks
=> feat(Handlebars): block whitespace control

.github/workflows/ci.yml
#ci
https://github.com/alandefreitas/cpp-actions/releases/tag/v1.8.8
=> cpp-actions v1.8.8

docs/modules/ROOT/pages/config-file.adoc
=> update documentation on filters

docs/modules/ROOT/pages/usage.adoc
=> exposition on system dependencies

docs/extensions/mrdocs-releases.js
=> Releases documentation page includes macOs

src/lib/AST/ASTVisitor.cpp, test-files/golden-tests/core/libcxx.adoc, test-files/golden-tests/core/libcxx.html, test-files/golden-tests/core/libcxx.xml, test-files/golden-tests/metadata/sfinae.adoc, test-files/golden-tests/metadata/sfinae.html, test-files/golden-tests/metadata/sfinae.xml, test-files/golden-tests/snippets/sqrt.adoc, test-files/golden-tests/snippets/sqrt.html, test-files/golden-tests/snippets/sqrt.xml
=> SFINAE return type constraints

src/lib/AST/ASTVisitor.cpp, src/lib/AST/ASTVisitor.hpp, src/lib/AST/ClangHelpers.cpp, src/lib/AST/ClangHelpers.hpp, src/lib/Metadata/Finalizers/OverloadsFinalizer.cpp, test-files/golden-tests/javadoc/copydoc/param-types.adoc, test-files/golden-tests/javadoc/copydoc/param-types.html, test-files/golden-tests/javadoc/copydoc/param-types.xml, test-files/golden-tests/symbols/function/auto.adoc, test-files/golden-tests/symbols/function/auto.cpp, test-files/golden-tests/symbols/function/auto.html, test-files/golden-tests/symbols/function/auto.xml, test-files/golden-tests/symbols/function/function-template.adoc, test-files/golden-tests/symbols/function/function-template.html, test-files/golden-tests/symbols/function/function-template.xml
=> support implicit templates

include/mrdocs/ADT/Polymorphic.hpp
=> Fix the documentation of the default deleter for Polymorphic

bootstrap.py
These were the last two issues causing problems on Windows.
=> Installation: ensure git symlinks and vcvarsall environment
